# Site settings
title: Ali Bachar
description: 'Developer'
url: 'http://AliB-2512.github.io'
baseurl: ''
profilepic: '/images/ali.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '9838e08a8c.js'

author:
  name: 'Ali Bachar'
  email: dev.alib@outlook.com
  twitter_username: AliBPt1
#  facebook_username: joshgerdes
  github_username:  AliB-2512
  linkedin_username:  ali-bachar
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
